name: RouterOS for UTM (Intel)
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: "7.17.2"
      script:
        required: true
        type: string
        default: "no-gdisk"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install packages into building machine
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip qemu-utils rsync gdisk dosfstools parted genisoimage zip
      
      - name: Set version based on manually triggered build
        id: get-version-custom
        run: |
          echo "ROSVER=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      
      - name: Print versions for debugging
        run: |
          echo "Build using $ROSVER with ${{ github.event.inputs.script }} script"  

      - name: Run ${{ github.event.inputs.script }} script to download and modify the CHR images
        run: sudo bash ${{ github.event.inputs.script }} $ROSVER

      - name: Copy re-packaged CHR to RouterOS.utm/Data
        run: cp chr-${{ env.ROSVER }}.uefi-fat.raw ./RouterOS.utm/Data/chr-uefi-fat.raw
      
      - name: Create a ZIP file
        run: zip -r RouterOS.utm.zip RouterOS.utm

      - name: Create artifact using RouterOS.utm directory
        uses: actions/upload-artifact@v4
        with:
          name: RouterOS.utm
          path: ./RouterOS.utm
      - name: Push git tag to save builder's code (required for release)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag v${{ env.ROSVER }}
          echo "Build${{ github.run_id }}-${{github.event.inputs.script}}"
          git push origin v${{ env.ROSVER }}
      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.ROSVER }}
          release_name: ${{ env.ROSVER }}-${{ github.event.inputs.script }} 
          body: "UTM packaged fat-chr images.  See https://github.com/tikoci/fat-chr for details on image used."
          draft: false
          prerelease: true
      - name: Upload CHR RAW image to release
        id: upload-release-asset-raw
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./RouterOS.utm.zip
          asset_name: RouterOS.utm.zip
          asset_content_type: application/octet-stream
